### ISSUE TITLE
JSON standardization

### ISSUE THREAD

**Issue by zleyyij** [Spec-ify/specify#33]
This applies to both specified and specify, I'm putting it here. This change entails standardizing and cleaning up the Specify json.
# TODO
- [ ] Write a broad summary of the json, breaking it down into various parts and clarifying keys when needed. Units should be specified(mega, mebi and so on).
- [ ] On the specified side, convert WorkingSet to me(ga|bi)bytes and label in the viewer. Drives are also measured in bytes then converted specified side, so I feel this is fine.
- [ ] Ensure all references to datetime and elapsed time are in Unix time, or decide on a standard to abide by (eg: 8601). This affects InstalledApps, startuptasks, possibly bios release date, DHCP info
- [ ] Remove redundant data from the JSON, or add a clarifying reason in the json doc explaining why it's needed (see ScheduledTasks Path and Name) for one instance

More can be added, this should be enough to start.

**Comment by zleyyij** [comment]
ISO 8601/DateTime object please
